### ISSUE TITLE
Relative Links (Jekyll/Markdown/Github)

### ISSUE THREAD

**Issue by bpasanek** [bpasanek/puzzlepoesis#1]
Brad can get relative links working locally, but when he pushes them to Github, they break. What gives?

These point into the void:
```
1. [Sonnet 16](/puzzlepoems/sonnet16.html), Neal Curtis
2. ["Ah! Sun-Flower,"](/puzzlepoems/sunflower.html) Brad Pasanek
```
Were previously written 
```
1. [Sonnet 16](../puzzlepoems/sonnet16.html), Neal Curtis
2. ["Ah! Sun-Flower,"](../puzzlepoems/sunflower.html) Brad Pasanek
```

**Comment by jeremyboggs** [comment]
One thing we'll need to do is set `baseurl` in the `_config.yml` to help with some of the relative linking.

**Comment by bpasanek** [comment]
Ok, did so (configged). That means I'm almost there?

Here's the directory structure:
[cid:8B37F163-4769-401D-BFEC-8C9E8323D859]

If I link from my index down a folder into puzzlepoems, it should look like this, right?
![Sonnet 16](/images/sonnet16.html) # not working on gh, was working locally

Or up from that page and across into an images folder?
![Sonnet 16 in pieces](/images/sonnet16pieces.jpg) # not working on gh, worked locally

Also a back button from sonnet16.html:
![Back](..) # not working on gh, worked locally

----------------------------
Brad Pasanek
Associate Professor
Director of Undergraduate Study
English Department, University of Virginia

Office hours: Monday, 11:30 am to 12:30pm, and Wednesday, 12:30 to 2:00pm.
Book an appointment at https://pasanek.youcanbook.me

office: Bryan 427
call: 434.924.6644
web: bradpasanek.com<http://bradpasanek.com> | metaphorized.net<http://metaphorized.net>

On Sep 27, 2017, at 9:17 AM, Jeremy Boggs <notifications@github.com<mailto:notifications@github.com>> wrote:


One thing we'll need to do is set baseurl in the _config.yml to help with some of the relative linking.

**Comment by bpasanek** [comment]
Using dots works both locally and on gh. 

From `sunflower.html` file back to index and over to image folder:
```
![Ah! Sunflower](../images/sunflower.jpg)
[<< Back <<](..)
```
