### ISSUE TITLE
Remove _sass directory

### ISSUE THREAD

**Issue by jeremyboggs** [bpasanek/puzzlepoesis#12]
Includes for Sass are pull from the `scss` directory, so no need for this other directory.

**Comment by jeremyboggs** [comment]
I'd guess this is an artifact of forking an existing project or theme, where they offered the same files in both SASS and SCSS syntax?

**Comment by bpasanek** [comment]
The double directories are my fault. When I got started I couldn't tell which was what and was having problems altering the CSS. -- Thanks for the delete!
